export const metadata={title:'Sport og fritid | Grundejerforeningen Ravnsbjerg',description:'Hall’n og idrætsmuligheder tæt på Ravnsbjerg i Hammerum-Gjellerup.'}

const activities=['Badminton','Bordtennis','Fitness','Fodbold','Gymnastik','Håndbold','Kroket','Linedance','Motion & Kultur','Padel','Skydning','Spinning','Svømning','Tennis','Volleyball','Squash']

export default function Sport(){return <main>
<section className="areaHero"><div className="wrap areaHeroGrid"><div><p className="eyebrow">Hammerum · Gjellerup</p><h1>Sport og fritid</h1><p className="lead">En stor del af det lokale idrætsliv ligger samlet omkring Hall’n i Hammerum.</p><p className="areaIntro">Her er et kort overblik. Brug foreningernes egne sider til aktuelle hold, tider og tilmelding.</p></div><div className="sportHeroMark"><span>⚽</span><span>🏊</span><span>🏸</span><span>🏋️</span></div></div></section>

<section className="section"><div className="wrap areaFeature"><div><p className="eyebrow">Frølundvej 41</p><h2>Hall’n</h2><p className="leadSmall">Hall’n er det lokale samlingspunkt for mange sports- og fritidsaktiviteter.</p><p>Der er både indendørs og udendørs aktiviteter, og mange af de lokale foreninger holder til her.</p><div className="pageActions"><a className="button primary" href="https://halln.dk/sport-fritid/" target="_blank" rel="noreferrer">Se hold og aktiviteter</a><a className="button secondary" href="https://www.google.com/maps/search/?api=1&query=Hall%27n+Fr%C3%B8lundvej+41+7400+Herning" target="_blank" rel="noreferrer">Se Hall’n på kort</a></div></div><div className="mapFrame compactMap"><iframe title="Kort til Hall'n" src="https://www.google.com/maps?q=Fr%C3%B8lundvej+41,+7400+Herning&z=14&output=embed" loading="lazy" referrerPolicy="no-referrer-when-downgrade"></iframe></div></div></section>

<section className="section soft"><div className="wrap"><div className="sectionHead"><div><p className="eyebrow">Aktiviteter</p><h2>Det kan du blandt andet gå til</h2></div><p>Listen er baseret på Hall’ns egen oversigt.</p></div><div className="activityGrid">{activities.map(a=><div className="activityChip" key={a}>{a}</div>)}</div></div></section>

<section className="section cream"><div className="wrap areaFeature"><div><p className="eyebrow">Uden hal</p><h2>Gå, løb eller cykl</h2><p className="leadSmall">Fra Ravnsbjerg er der også gode muligheder for motion uden et medlemskab.</p><p>Lunden, Nabkærstien og Gjellerup Enge hænger sammen med stier i området. Underlaget skifter mellem asfalt, grus og trampesti.</p><a className="button secondary" href="/omraadet">Se området og stierne</a></div><div className="sportNature"><span>🚶</span><span>🏃</span><span>🚲</span></div></div></section>

<section className="section"><div className="wrap"><div className="sectionHead"><div><p className="eyebrow">Hvis du leder efter mere</p><h2>Sportscenter Herning</h2></div><p>Der er flere idrætsgrene og baner i Herning, hvis tilbuddet ikke findes lokalt.</p></div><a className="button secondary" href="https://www.sportscenterherning.dk/" target="_blank" rel="noreferrer">Sportscenter Herning</a></div></section>

<section className="areaSources"><div className="wrap"><h3>Aktuelle oplysninger</h3><p>Hold og tider ændrer sig. Tjek Hall’n og de enkelte foreninger, før du tager af sted.</p><div className="docLinks"><a href="https://halln.dk/sport-fritid/" target="_blank" rel="noreferrer">Hall’n →</a><a href="https://www.sportscenterherning.dk/" target="_blank" rel="noreferrer">Sportscenter Herning →</a></div></div></section>
</main>}
