export const metadata={title:'Hall’n | Grundejerforeningen Ravnsbjerg',description:'Lokale sports- og fritidsmuligheder i Hall’n i Hammerum-Gjellerup.'}

const activities=['Badminton','Bordtennis','Fitness','Fodbold','Gymnastik','Håndbold','Kroket','Linedance','Motion & Kultur','Padel','Skydning','Spinning','Svømning','Tennis','Volleyball','Squash']

export default function Sport(){return <main>
<section className="areaHero"><div className="wrap areaHeroGrid"><div><p className="eyebrow">Sport og fritid · lokalt</p><h1>Hall’n</h1><p className="lead">Det meste lokale idrætsliv i Hammerum-Gjellerup er samlet i og omkring Hall’n.</p><p className="areaIntro">Hall’n ligger på Frølundvej 41 ved Lindbjergskolen. Herfra finder du videre til de foreninger, hold og aktiviteter, der er aktuelle lige nu.</p><div className="pageActions"><a className="button primary" href="https://halln.dk/sport-fritid/" target="_blank" rel="noreferrer">Se hold og aktiviteter</a></div></div><div className="mapFrame compactMap"><iframe title="Kort til Hall'n" src="https://www.google.com/maps?q=Fr%C3%B8lundvej+41,+7400+Herning&z=15&output=embed" loading="lazy" referrerPolicy="no-referrer-when-downgrade"></iframe></div></div></section>

<section className="section"><div className="wrap"><div className="sectionHead"><div><p className="eyebrow">Hvad kan man gå til?</p><h2>Det meste er her</h2></div><p>Hold, tider og tilmelding ændrer sig, så brug Hall’ns egen side, når du vil videre.</p></div><div className="activityGrid sportActivities">{activities.map(a=><div className="activityChip" key={a}>{a}</div>)}</div><div className="pageActions"><a className="button primary" href="https://halln.dk/sport-fritid/" target="_blank" rel="noreferrer">Hall’n – sport og fritid →</a><a className="button secondary" href="/omraadet">Tilbage til Ny i Ravnsbjerg</a></div></div></section>
</main>}
