export const metadata={title:'Sport og fritid | Grundejerforeningen Ravnsbjerg',description:'Sport, haller og fritidsmuligheder tæt på Ravnsbjerg i Hammerum-Gjellerup.'}

const activities=['Badminton','Bordtennis','Fitness','Fodbold','Gymnastik','Håndbold','Kroket','Linedance','Motion & Kultur','Padel','Skydning','Spinning','Svømning','Tennis','Volleyball','Squash']

export default function Sport(){return <main>
<section className="areaHero"><div className="wrap areaHeroGrid"><div><p className="eyebrow">Hammerum · Gjellerup</p><h1>Sport og fritid</h1><p className="lead">Der er usædvanligt mange idrætsmuligheder tæt på Ravnsbjerg. Det meste lokale foreningsliv er samlet i og omkring Hall’n i Hammerum.</p><p className="areaIntro">Her kan både børn og voksne finde noget at gå til – fra fodbold og gymnastik til svømning, padel, fitness og badminton.</p></div><div className="sportHeroMark"><span>⚽</span><span>🏊</span><span>🏸</span><span>🏋️</span></div></div></section>

<section className="section"><div className="wrap areaFeature"><div><p className="eyebrow">Det lokale samlingspunkt</p><h2>Hall’n</h2><p className="leadSmall">Hall’n på Frølundvej 41 er centrum for en stor del af idræts- og foreningslivet i Hammerum-Gjellerup.</p><p>Hall’n samler både indendørs og udendørs aktiviteter og fungerer som hjemmebane for en række lokale foreninger. Det betyder, at mange aktiviteter kan klares i nærområdet i stedet for inde i Herning.</p><div className="docLinks"><a href="https://halln.dk/sport-fritid/" target="_blank" rel="noreferrer">Se aktiviteter hos Hall’n →</a><a href="https://www.google.com/maps/search/?api=1&query=Hall%27n+Fr%C3%B8lundvej+41+7400+Herning" target="_blank" rel="noreferrer">Åbn i Google Maps →</a></div></div><div className="mapFrame compactMap"><iframe title="Kort til Hall'n" src="https://www.google.com/maps?q=Fr%C3%B8lundvej+41,+7400+Herning&z=14&output=embed" loading="lazy" referrerPolicy="no-referrer-when-downgrade"></iframe></div></div></section>

<section className="section soft"><div className="wrap"><div className="sectionHead"><div><p className="eyebrow">Hvad kan man gå til?</p><h2>En ret lang liste</h2></div><p>Aktiviteterne nedenfor er dem, Hall’n selv oplister.</p></div><div className="activityGrid">{activities.map(a=><div className="activityChip" key={a}>{a}</div>)}</div></div></section>

<section className="section cream"><div className="wrap"><div className="sectionHead"><div><p className="eyebrow">Lidt længere væk</p><h2>Sportscenter Herning</h2></div><p>Hvis den lokale aktivitet ikke findes i Hall’n, er der endnu flere muligheder i Herning.</p></div><div className="areaFacts"><article><span>Haller</span><h3>Bold og bane</h3><p>Sportscenter Herning har multihaller med blandt andet håndbold, badminton, volleyball, basket, tennis, indendørs fodbold og floorball.</p></article><article><span>Klubber</span><h3>Mange idrætter</h3><p>Centret huser klubber inden for blandt andet badminton, boksning, brydning, floorball, gymnastik, judo, skydning, squash, taekwondo og volleyball.</p></article><article><span>Privat</span><h3>Book en bane</h3><p>Centret oplyser, at private også kan booke baner og benytte flere af faciliteterne.</p></article></div><div className="docLinks sourceLinks"><a href="https://www.sportscenterherning.dk/" target="_blank" rel="noreferrer">Sportscenter Herning →</a></div></div></section>

<section className="section"><div className="wrap areaFeature"><div><p className="eyebrow">Uden hal</p><h2>Motion lige fra kvarteret</h2><p className="leadSmall">Man behøver selvfølgelig ikke melde sig ind nogen steder for at komme ud.</p><p>Fra Ravnsbjerg er der adgang videre mod Lunden, Nabkærstien og Gjellerup Enge, hvor man kan gå, løbe eller cykle ad asfalt-, grus- og trampestier.</p><a className="button secondary" href="/omraadet">Se området og stierne</a></div><div className="sportNature"><span>🚶</span><span>🏃</span><span>🚲</span></div></div></section>

<section className="areaSources"><div className="wrap"><h3>Kilder og aktuelle hold</h3><p>Hold, tider og tilbud ændrer sig. Brug derfor foreningernes egne sider, når du vil se det aktuelle program.</p><div className="docLinks"><a href="https://halln.dk/sport-fritid/" target="_blank" rel="noreferrer">Hall’n – Sport & Fritid →</a><a href="https://www.sportscenterherning.dk/" target="_blank" rel="noreferrer">Sportscenter Herning →</a></div></div></section>
</main>}
