const museumHero='https://museummidtjylland.dk/wp-content/uploads/2024/11/hammerum-pigen-ansigt-til-ansigt-klosterlund-museum-1-scaled-1045x800-1.jpg'
const museumDress='https://museummidtjylland.dk/wp-content/uploads/2021/07/hammerum-pigen-klosterlund-museum-scaled-1045x800-1.jpg'

export const metadata={title:'Hammerum-pigen | Grundejerforeningen Ravnsbjerg',description:'Historien om Hammerum-pigen og gravpladsen ved Ny Gjellerupvej.'}

export default function Hammerumpigen(){return <main>
<section className="areaHero historyHero"><div className="wrap areaHeroGrid"><div><p className="crumb"><a href="/omraadet">Om området</a><span>›</span> Hammerum-pigen</p><p className="eyebrow">Lokalhistorie · ca. år 200</p><h1>Hammerum-pigen</h1><p className="lead">En kvindegrav fra romersk jernalder, fundet på Ny Gjellerupvej.</p><p className="areaIntro">Gravpladsen blev undersøgt i 1993. Hår, tekstiler og træ var bevaret så godt, at fundet kunne undersøges i detaljer.</p></div><div className="areaHeroPhoto"><img src={museumHero} alt="Hammerum-pigen i udstillingen på Klosterlund Museum"/><small className="photoCredit">Foto: Museum Midtjylland</small></div></div></section>

<section className="section"><div className="wrap areaFeature"><div><p className="eyebrow">Fundet</p><h2>Syv grave</h2><p className="leadSmall">Museum Midtjylland fandt syv jordfæstegrave fra omkring år 200.</p><p>Tre grave var så velbevarede, at de blev taget op som hele præparater. Det særlige var især de organiske materialer, som normalt forsvinder i jorden.</p><p>Fundet blev gjort ved Ny Gjellerupvej, få kilometer fra Ravnsbjerg.</p></div><div className="historyQuote"><span>1993</span><p>Gravpladsen ved Ny Gjellerupvej blev udgravet.</p></div></div></section>

<section className="section soft"><div className="wrap areaFeature"><div className="areaHeroPhoto historyPhoto"><img src={museumDress} alt="Hammerum-pigens dragt og fletning" loading="lazy"/><small className="photoCredit">Foto: Museum Midtjylland</small></div><div><p className="eyebrow">Dragten</p><h2>Dragt og frisure</h2><p className="leadSmall">Store dele af dragten og håret var bevaret.</p><p>Kvinden bar blandt andet en rød- og hvidstribet uldkjole og et hvidt sjal med en rød stribe. Håret var sat op i en omhyggelig frisure.</p><p>Undersøgelser tyder på, at ulden kom fra lokale får. Frisuren havde ligheder med moden i Romerriget, mens tøjet var lavet lokalt.</p></div></div></section>

<section className="section"><div className="wrap"><div className="areaFacts"><article><span>ca. 200</span><h3>Dateringen</h3><p>Gravene stammer fra romersk jernalder.</p></article><article><span>16 år</span><h3>Arbejdet</h3><p>De skrøbelige tekstiler tog mange år at fritlægge og undersøge.</p></article><article><span>I dag</span><h3>Klosterlund Museum</h3><p>Hammerum-pigen kan opleves i museets udstilling.</p></article></div></div></section>

<section className="section cream"><div className="wrap areaFeature"><div><p className="eyebrow">Læs mere</p><h2>Museum Midtjylland</h2><p className="leadSmall">Museet har samlet historien om fundet, dragten og forskningen.</p><p>Der er også udgivet en faglig bog om hele gravpladsen: <em>The Hammerum Burial Site. Customs and Clothing in the Roman Iron Age</em>.</p><div className="pageActions"><a className="button primary" href="https://museummidtjylland.dk/hammerum-pigen/">Læs om Hammerum-pigen</a><a className="button secondary" href="https://museummidtjylland.dk/klosterlund-museum/">Klosterlund Museum</a></div><p className="smallNote">Tekst og billeder tager udgangspunkt i Museum Midtjyllands formidling af fundet.</p></div><div className="historyQuote"><span>≈ 200</span><p>e.Kr. · romersk jernalder</p></div></div></section>
</main>}
