export const metadata={title:'Hammerum-pigen | Grundejerforeningen Ravnsbjerg',description:'Historien om Hammerum-pigen og gravpladsen ved Ny Gjellerupvej.'}

export default function Hammerumpigen(){return <main>
<section className="areaHero historyHero"><div className="wrap areaHeroGrid"><div><p className="eyebrow">Lokalhistorie · ca. år 200</p><h1>Hammerum-pigen</h1><p className="lead">For omkring 1.800 år siden blev en ung kvinde begravet tæt på det område, vi i dag kender som Hammerum og Gjellerup.</p><p className="areaIntro">Da gravpladsen ved Ny Gjellerupvej blev undersøgt i 1993, fandt arkæologerne usædvanligt velbevarede rester af blandt andet hår, tekstiler og træ. En af gravene blev senere kendt som Hammerum-pigen.</p></div><div className="historyMark"><span>≈ 200</span><small>e.Kr.</small></div></div></section>

<section className="section"><div className="wrap areaFeature"><div><p className="eyebrow">Fundet</p><h2>Syv grave ved Ny Gjellerupvej</h2><p className="leadSmall">Museum Midtjylland undersøgte i 1993 en lille gravplads med syv jordfæstegrave fra romersk jernalder.</p><p>Tre af gravene var så velbevarede, at de blev taget op som hele præparater. Det særlige ved stedet var de organiske materialer: træ, hår og tekstiler, som normalt forsvinder i jorden.</p><p>Det gav arkæologerne en sjælden mulighed for at komme helt tæt på, hvordan mennesker i Midtjylland var klædt, begravet og udsmykket omkring år 200.</p></div><div className="mapFrame compactMap"><iframe title="Ny Gjellerupvej i Hammerum" src="https://www.google.com/maps?q=Ny+Gjellerupvej,+7400+Herning&z=14&output=embed" loading="lazy" referrerPolicy="no-referrer-when-downgrade"></iframe></div></div></section>

<section className="section soft"><div className="wrap"><div className="sectionHead"><div><p className="eyebrow">Hvorfor er hun særlig?</p><h2>Hår, tekstiler og en frisure</h2></div><p>Det er især bevaringen, der gør fundet usædvanligt.</p></div><div className="areaFacts"><article><span>Hår</span><h3>En bevaret frisure</h3><p>Hammerum-pigen blev fundet med bevaret hår og en kunstfærdig frisure. Det giver et sjældent direkte indblik i personlig fremtoning fra romersk jernalder.</p></article><article><span>Tekstil</span><h3>Tøj fra jernalderen</h3><p>De velbevarede tekstiler har gjort gravpladsen vigtig for forskningen i dragter, vævning og tekstilhåndværk.</p></article><article><span>Gravskik</span><h3>Et lokalt øjeblik</h3><p>Gravene fortæller ikke bare om én person, men om skikke og hverdagsliv blandt mennesker, der boede her for næsten to årtusinder siden.</p></article></div></div></section>

<section className="section cream"><div className="wrap areaFeature"><div><p className="eyebrow">Fra fund til forskning</p><h2>En hel bog om gravpladsen</h2><p className="leadSmall">Museum Midtjylland har sammen med Jysk Arkæologisk Selskab udgivet <em>The Hammerum Burial Site. Customs and Clothing in the Roman Iron Age</em>.</p><p>Publikationen samler forskningsresultaterne fra gravpladsen og har særlig fokus på Hammerum-pigen, tekstilerne og gravskikkene.</p><div className="docLinks"><a href="https://museummidtjylland.dk/bogudgivelse-the-hammerum-burial-site/" target="_blank" rel="noreferrer">Læs Museum Midtjyllands historie →</a></div></div><div className="historyQuote"><span>1993</span><p>Gravpladsen ved Ny Gjellerupvej bliver undersøgt.</p></div></div></section>

<section className="section"><div className="wrap"><div className="sectionHead"><div><p className="eyebrow">Tættere end man tror</p><h2>Historie under fødderne</h2></div><p>Fundet er en god påmindelse om, at området omkring Ravnsbjerg, Hammerum og Gjellerup har været beboet længe før de nuværende villaveje kom til.</p></div><p className="leadSmall historyClosing">Hammerum-pigen er ikke en myte eller en lokal fortælling, der er vokset med tiden. Hun er et konkret arkæologisk fund fra vores nærområde – og et af de fund, der har givet forskerne ny viden om livet i Midtjylland i romersk jernalder.</p></div></section>

<section className="areaSources"><div className="wrap"><h3>Læs mere</h3><p>Oplysningerne på siden bygger på Museum Midtjyllands beskrivelse af gravpladsen og deres forskningspublikation.</p><div className="docLinks"><a href="https://museummidtjylland.dk/bogudgivelse-the-hammerum-burial-site/" target="_blank" rel="noreferrer">Museum Midtjylland – The Hammerum Burial Site →</a><a href="https://museummidtjylland.dk/arkaeologi/" target="_blank" rel="noreferrer">Museum Midtjylland – Arkæologi →</a></div></div></section>
</main>}
