import {INaturalistEmbed} from '../../components/INaturalistEmbed'

const enge='/images/gjellerup-enge.webp'
const engeTrail='/images/gjellerup-enge-sti.avif'
const engePanorama='/images/gjellerup-enge-panorama.avif'
const engeView='/images/gjellerup-enge-udsigt.avif'
const engeReport='https://398e19644f.clvaw-cdnwnd.com/924937a717deb337e31c66e81824097a/200000012-376e1376e4/%C3%85rsberetning%20for%20Gjellerup%20enge%202024.pdf?ph=398e19644f'
const title='Gjellerup Enge | Grundejerforeningen Ravnsbjerg'
const description='Naturprojektet Gjellerup Enge ved Ravnsbjerg: stier, natur, iNaturalist og nogle af de arter, der er registreret i området.'
export const metadata={title,description,openGraph:{title,description,url:'/gjellerup-enge'}}

const wildlife=[
 {name:'Tredækker',latin:'Gallinago media',text:'En sjælden trækgæst, registreret i Gjellerup Enge i 2025.',img:'https://commons.wikimedia.org/wiki/Special:FilePath/Great%20Snipe%20%28Gallinago%20media%29%20%2814366171534%29.jpg',credit:'Ron Knight · CC BY 2.0',creditUrl:'https://commons.wikimedia.org/wiki/File:Great_Snipe_(Gallinago_media)_(14366171534).jpg'},
 {name:'Vibe',latin:'Vanellus vanellus',text:'En af de fugle, man kan opleve på de åbne og fugtige arealer.',img:'https://commons.wikimedia.org/wiki/Special:FilePath/Northern%20Lapwing%20Vanellus%20vanellus.jpg',credit:'Ivan Vezenković · CC0',creditUrl:'https://commons.wikimedia.org/wiki/File:Northern_Lapwing_Vanellus_vanellus.jpg'},
 {name:'Sanglærke',latin:'Alauda arvensis',text:'Høres og ses over de åbne enge og græsarealer.',img:'https://commons.wikimedia.org/wiki/Special:FilePath/Eurasian%20Skylark%20%28Alauda%20arvensis%29%20%2850715699017%29.jpg',credit:'Imran Shah · CC BY-SA 2.0',creditUrl:'https://commons.wikimedia.org/wiki/File:Eurasian_Skylark_(Alauda_arvensis)_(50715699017).jpg'},
 {name:'Bæver',latin:'Castor fiber',text:'Bæver blev registreret ved Hammerum Bæk i området i 2026.',img:'https://commons.wikimedia.org/wiki/Special:FilePath/Beaver%20-%20Eurasian%20beaver%20-%20Castor%20fiber.jpg',credit:'Bouke ten Cate · CC BY 4.0',creditUrl:'https://commons.wikimedia.org/wiki/File:Beaver_-_Eurasian_beaver_-_Castor_fiber.jpg'},
 {name:'Okkergul pletvinge',latin:'Melitaea cinxia',text:'Sommerfuglen blev registreret på Ege Carpets arealer i Gjellerup Enge i 2025.',img:'https://commons.wikimedia.org/wiki/Special:FilePath/Melitaea%20cinxia.png',credit:'Niclas Fritzén · CC BY 2.5',creditUrl:'https://commons.wikimedia.org/wiki/File:Melitaea_cinxia.png'}
]

export default function GjellerupEnge(){return <main>
<section className="areaHero"><div className="wrap areaHeroGrid"><div><p className="crumb"><a href="/omraadet">Om området</a><span>›</span> Gjellerup Enge</p><p className="eyebrow">Natur lige ved Ravnsbjerg</p><h1>Gjellerup Enge</h1><p className="lead">144 hektar sammenhængende natur med enge, vådområder, stier og græssende dyr.</p><p className="areaIntro">Området er udviklet i samarbejde mellem blandt andre Den Danske Naturfond, Herning Kommune, Herning Vand, Ege Carpets og Grundejerforeningen Ravnsbjerg.</p></div><div className="areaHeroPhoto"><img src={enge} width="287" height="510" alt="Natur ved Gjellerup Enge" fetchPriority="high"/></div></div></section>

<section className="section"><div className="wrap"><div className="engeIntro"><p className="leadSmall">Gjellerup Enge består blandt andet af enge, kær, overdrev, skov, krat og små vådområder. Hammerum Bæk løber gennem den sydlige del af området.</p><p>Der er omkring tre kilometer stier, og heste og kvæg græsser i området. Regnvandsbassiner fra kloaksepareringen i Hammerum er blevet en del af landskabet, og jord fra bassinerne er brugt til en cirka 10 meter høj udkigsbakke.</p><p>Det er altså både et naturprojekt, et sted at gå en tur og en del af områdets håndtering af regnvand.</p><div className="docLinks"><a href="https://naturfonden.dk/natur/gjellerup-enge/">Læs hos Den Danske Naturfond →</a><a href={engeReport}>Årsberetning 2024 · PDF →</a></div></div><div className="areaFacts fourFacts"><article><span>144 ha</span><h3>Natur</h3><p>Enge, kær, overdrev, skov, krat og vådområder.</p></article><article><span>ca. 3 km</span><h3>Stier</h3><p>Til fods gennem området, også gennem indhegninger med dyr.</p></article><article><span>10 m</span><h3>Udkigsbakke</h3><p>Bygget af jord fra de nye regnvandsbassiner.</p></article><article><span>1.203</span><h3>Arter</h3><p>Registreret på iNaturalist ved udgangen af 2025.</p></article></div><div className="areaGallery"><img src={engeTrail} alt="Sti gennem skoven ved Gjellerup Enge" loading="lazy"/><img src={engePanorama} alt="Panorama over sø og enge i Gjellerup Enge" loading="lazy"/><img src={engeView} alt="Udsigt over søen i Gjellerup Enge" loading="lazy"/></div></div></section>

<section className="section soft"><div className="wrap areaFeature"><div><p className="eyebrow">iNaturalist</p><h2>Se fundene</h2><p className="leadSmall">Lokale naturfolk og andre besøgende registrerer løbende dyr, planter og svampe i Gjellerup Enge.</p><p>Ved udgangen af 2025 var der registreret 1.203 arter på iNaturalist. Du kan enten åbne projektet direkte eller hente visningen her på siden.</p><div className="pageActions"><a className="button primary" href="https://www.inaturalist.org/projects/gjellerup-enge">Åbn Gjellerup Enge på iNaturalist</a></div><p className="smallNote">Der findes også registreringer på <a href="https://arter.dk/faellesskaber/2017">Arter.dk</a>.</p></div><INaturalistEmbed/></div></section>

<section className="section"><div className="wrap"><div className="sectionHead"><div><p className="eyebrow">Dyreliv</p><h2>Det kan du opleve</h2></div><p>Et par eksempler blandt de mange registrerede arter.</p></div><div className="wildlifeGrid">{wildlife.map(w=><article className="wildlifeCard" key={w.name}><img src={w.img} alt={w.name} loading="lazy"/><div className="wildlifeBody"><p className="eyebrow">{w.latin}</p><h3>{w.name}</h3><p>{w.text}</p><a href={w.creditUrl}>Foto: {w.credit}</a></div></article>)}</div><p className="smallNote">Artsbillederne er illustrationsfotos og er ikke nødvendigvis taget i Gjellerup Enge.</p></div></section>
</main>}