import {news,board,documents} from '../data/content'
import {ContactForm} from '../components/ContactForm'

const heart='https://398e19644f.clvaw-cdnwnd.com/924937a717deb337e31c66e81824097a/200000008-2f36b2f36d/Hjertestarter.jpeg?ph=398e19644f'
const enge='https://398e19644f.clvaw-cdnwnd.com/924937a717deb337e31c66e81824097a/200000010-c8d10c8d12/IMG_1053.avif?ph=398e19644f'
const lunden1='https://398e19644f.clvaw-cdnwnd.com/924937a717deb337e31c66e81824097a/200000035-7bee97beec/ea6e5aa3-1b01-47d3-8fd4-1cae02db549f.jpeg?ph=398e19644f'
const lunden2='https://398e19644f.clvaw-cdnwnd.com/924937a717deb337e31c66e81824097a/200000036-936cb936cd/df6156b8-e6cd-4fd6-a62d-a817fed3fcd0-8.jpeg?ph=398e19644f'

export default function Home(){return <main>
<section className="hero"><div className="wrap heroGrid"><div><p className="eyebrow">Grundejerforeningen · Gjellerup</p><h1>Ravnsbjerg</h1><p className="lead">Her finder du nyt fra området, Lunden, vedtægter og kontakt til bestyrelsen.</p><div className="actions"><a className="button primary" href="#nyheder">Se seneste nyt</a><a className="button secondary" href="#kontakt">Kontakt bestyrelsen</a></div></div><div className="visual photoHero"><img src={lunden1} alt="Lunden ved Ravnsbjerg"/><div className="stat"><b>117</b><span>husstande i området</span></div></div></div></section>

<section className="quick"><div className="wrap quickGrid"><a href="#hjertestarter"><b>♥</b><span><strong>Hjertestarter</strong><small>Ravnsbjerg Krat 2</small></span><i>→</i></a><a href="/vedtaegter"><b>§</b><span><strong>Vedtægter</strong><small>Gældende ordlyd</small></span><i>→</i></a><a href="#generalforsamling"><b>◎</b><span><strong>Generalforsamling</strong><small>Frister og referat 2026</small></span><i>→</i></a><a href="#kontakt"><b>✉</b><span><strong>Kontakt</strong><small>Skriv til bestyrelsen</small></span><i>→</i></a></div></section>

<section id="nyheder" className="section"><div className="wrap"><div className="sectionHead"><div><p className="eyebrow">Nyt</p><h2>Fra Ravnsbjerg</h2></div><p>Det vigtigste fra foreningen og området omkring os.</p></div><div className="newsGrid">{news.map((n,i)=><article className={i===0?'card featured':'card'} key={n.title}>{i===1&&<img className="cardImage" src={enge} alt="Gjellerup Enge"/>}<span className="meta">{n.category}{n.date&&<> · {n.date}</>}</span><h3>{n.title}</h3><p>{n.body}</p>{i===1&&<a className="textLink" href={documents[3].href}>Årsberetning om Gjellerup Enge →</a>}</article>)}</div></div></section>

<section id="lunden" className="section soft"><div className="wrap split"><div className="lundenGallery"><img src={lunden1} alt="Lunden ved Ravnsbjerg"/><img src={lunden2} alt="Lunden ved Ravnsbjerg"/></div><div><p className="eyebrow">Fælles område</p><h2>Lunden</h2><p className="leadSmall">Lunden er foreningens grønne område. Som medlem får du en nøgle og kan blandt andet aflevere haveaffald.</p><h3>Haveaffald</h3><ul><li>Læg det så langt oppe til venstre som muligt.</li><li>Skub det ind over det, der allerede ligger.</li><li>Kun haveaffald.</li><li>Tag sække og poser med hjem.</li></ul><p>Jo bedre bunken bliver pakket, jo sjældnere skal vi betale for at få den skubbet sammen.</p><h3>Dokumenter om Lunden</h3><div className="docLinks"><a href={documents[1].href}>Andelsbevis →</a><a href={documents[2].href}>Skøde →</a></div></div></div></section>

<section id="foreningen" className="section cream"><div className="wrap infoGrid"><div><p className="eyebrow">Foreningen</p><h2>Om foreningen</h2><p className="leadSmall">Medlemskab er frivilligt, og næsten alle områdets 117 husstande er med.</p><p>Bestyrelsen tager sig af fælles forhold i kvarteret og af Lunden. Har du noget, vi bør se på, så tag fat i os.</p><a className="button secondary" href="/omraadet">Se mere om området</a></div><div className="stack"><article id="hjertestarter" className="infoCard photoCard"><img src={heart} alt="Foreningens hjertestarter"/><div><h3>Hjertestarter</h3><p>Den hænger på Ravnsbjerg Krat 2, bag den markerede dør til redskabsrummet i carporten til højre. Indgangen til Krat 2 er fra Ravnsbjergvej.</p></div></article><article id="generalforsamling" className="infoCard"><span>◎</span><div><h3>Generalforsamling</h3><p>Den ordinære generalforsamling holdes i første kvartal. Forslag skal være hos bestyrelsen skriftligt senest en uge før.</p><p>Indkaldelsen kommer på mail.</p><p><a href="/dokumenter/referat-generalforsamling-2026">Referat fra 11. marts 2026 →</a></p></div></article><article id="dokumenter" className="infoCard"><span>§</span><div><h3>Dokumenter</h3>{documents.map(d=><p key={d.title}><a href={d.href}>{d.title} →</a><br/><small>{d.meta}</small></p>)}</div></article></div></div></section>

<section id="bestyrelsen" className="section"><div className="wrap"><div className="sectionHead"><div><p className="eyebrow">Kontakt</p><h2>Bestyrelsen</h2></div><p>Den nuværende bestyrelse.</p></div><div className="boardGrid">{board.map(m=><article key={m.name}><span>{m.role}</span><h3>{m.name}</h3><p>{m.address}</p>{m.phone&&<a href={'tel:+45'+m.phone.replaceAll(' ','')}>{m.phone}</a>}</article>)}</div></div></section>

<section id="kontakt" className="contact"><div className="wrap contactGrid"><div><p className="eyebrow light">Kontakt</p><h2>Skriv til bestyrelsen</h2><p>Spørgsmål, forslag eller noget fra området, vi bør kende til? Send en besked.</p></div><ContactForm/></div></section>
</main>}
