import {news,board,documents} from '../data/content'
export default function Home(){return <main>
<section className="hero"><div className="wrap heroGrid"><div><p className="eyebrow">Gjellerup · Herning</p><h1>Et godt sted<br/>at bo <em>og mødes.</em></h1><p className="lead">Her finder du nyt fra Grundejerforeningen Ravnsbjerg, praktisk information om Lunden, vedtægter, generalforsamling og kontakt til bestyrelsen.</p><div className="actions"><a className="button primary" href="#nyheder">Se seneste nyt</a><a className="button secondary" href="#lunden">Om Lunden</a></div></div><div className="visual"><div className="sun"/><div className="hill back"/><div className="hill front"/><div className="path"/><div className="stat"><b>117</b><span>husstande i området</span></div></div></div></section>
<section className="quick"><div className="wrap quickGrid"><a href="#hjertestarter"><b>♥</b><span><strong>Hjertestarter</strong><small>Ravnsbjerg Krat 2</small></span><i>→</i></a><a href="#dokumenter"><b>§</b><span><strong>Vedtægter</strong><small>Gældende dokument</small></span><i>→</i></a><a href="#generalforsamling"><b>◎</b><span><strong>Generalforsamling</strong><small>Information og referater</small></span><i>→</i></a></div></section>
<section id="nyheder" className="section"><div className="wrap"><div className="sectionHead"><div><p className="eyebrow">Aktuelt</p><h2>Nyt fra Ravnsbjerg</h2></div><p>Praktisk information og nyt fra området samlet ét sted.</p></div><div className="newsGrid">{news.map((n,i)=><article className={i===0?'card featured':'card'} key={n.title}><span className="meta">{n.category} · {n.date}</span><h3>{n.title}</h3><p>{n.body}</p></article>)}</div></div></section>
<section id="lunden" className="section soft"><div className="wrap split"><div className="lundenVisual"><div className="moon"/><div className="meadow"/></div><div><p className="eyebrow">Vores fælles grønne område</p><h2>Lunden</h2><p className="leadSmall">Lunden er foreningens rekreative område. Medlemmer får en nøgle, som blandt andet giver adgang til pladsen for haveaffald.</p><h3>Husk ved haveaffald</h3><ul><li>Smid kun haveaffald.</li><li>Placér det så langt oppe til venstre som muligt.</li><li>Tag sække og poser med hjem igen.</li></ul></div></div></section>
<section id="foreningen" className="section cream"><div className="wrap infoGrid"><div><p className="eyebrow">Om foreningen</p><h2>Fælles interesser<br/>i kvarteret</h2><p className="leadSmall">Grundejerforeningen Ravnsbjerg er en frivillig forening. Området omfatter 117 husstande, og næsten alle er medlem. Bestyrelsen varetager medlemmernes fælles grundejerinteresser.</p></div><div className="stack"><article id="hjertestarter" className="infoCard"><span>♥</span><div><h3>Hjertestarter</h3><p>Ravnsbjerg Krat 2. I redskabsrummet i carporten til højre; døren er markeret.</p></div></article><article id="generalforsamling" className="infoCard"><span>◎</span><div><h3>Generalforsamling</h3><p>Afholdes hvert år i første kvartal. Forslag skal indsendes skriftligt senest én uge før.</p></div></article><article id="dokumenter" className="infoCard"><span>§</span><div><h3>Dokumenter</h3>{documents.map(d=><p key={d.title}><a href={d.href}>{d.title} →</a><br/><small>{d.meta}</small></p>)}</div></article></div></div></section>
<section id="bestyrelsen" className="section"><div className="wrap"><div className="sectionHead"><div><p className="eyebrow">Kontaktpersoner</p><h2>Bestyrelsen</h2></div><p>Konstitueret 8. april 2025.</p></div><div className="boardGrid">{board.map(m=><article key={m.name}><span>{m.role}</span><h3>{m.name}</h3><p>{m.address}</p>{m.phone&&<a href={'tel:+45'+m.phone.replaceAll(' ','')}>{m.phone}</a>}</article>)}</div></div></section>
<section id="kontakt" className="contact"><div className="wrap contactGrid"><div><p className="eyebrow light">Har du noget på hjerte?</p><h2>Kontakt bestyrelsen</h2><p>Spørgsmål, idéer eller noget i området, vi bør kende til? Tag fat i et bestyrelsesmedlem.</p></div><div className="contactBox"><strong>Kontaktformular</strong><p>Klargjort til næste trin, hvor vi kobler en sikker formular og administration på.</p></div></div></section>
</main>}
