import {news,board} from '../data/content'
import {ContactForm} from '../components/ContactForm'

const facebook='https://www.facebook.com/groups/ravnsbjerg'
const heart='/images/hjertestarter-hq.webp'
const heart700='/images/hjertestarter-700.webp'

export default function Home(){return <main>
<section className="hero"><div className="wrap heroGrid"><div><p className="eyebrow">Grundejerforeningen</p><h1>Ravnsbjerg</h1><p className="heroLocation">Gjellerup, Herning</p><p className="lead">Her finder du det vigtigste fra grundejerforeningen samlet ét sted.</p><nav className="heroQuick" aria-label="Genveje på forsiden"><a href="#hjertestarter"><b aria-hidden="true">♥</b><span><strong>Hjertestarter</strong><small>Ravnsbjerg Krat 2</small></span><i aria-hidden="true">→</i></a><a href="#kontakt"><b aria-hidden="true">✉</b><span><strong>Kontakt bestyrelsen</strong><small>Bestyrelse og besked</small></span><i aria-hidden="true">→</i></a><a href="/lunden"><b aria-hidden="true">↟</b><span><strong>Lunden</strong><small>Fælles grønt område</small></span><i aria-hidden="true">→</i></a><a href="/omraadet"><b aria-hidden="true">⌖</b><span><strong>Ny i Ravnsbjerg</strong><small>Om området</small></span><i aria-hidden="true">→</i></a><a href="/generalforsamling"><b aria-hidden="true">◎</b><span><strong>Generalforsamling</strong><small>Frister og referat</small></span><i aria-hidden="true">→</i></a><a href="/vedtaegter"><b aria-hidden="true">§</b><span><strong>Vedtægter</strong><small>Gældende ordlyd</small></span><i aria-hidden="true">→</i></a></nav></div><div className="visual photoHero"><video autoPlay muted loop playsInline preload="auto" poster="/images/hero-ravnsbjerg.avif" aria-label="Luftvideo over Ravnsbjerg og området omkring Gjellerup Enge"><source src="/ravnsbjerg-hero.mp4" type="video/mp4"/></video></div></div></section>

<section id="nyheder" className="section"><div className="wrap"><div className="sectionHead"><div><p className="eyebrow">Nyt</p><h2>Fra Ravnsbjerg</h2><p className="heroFacebook">Her lægger vi de større nyheder, som skal være nemme at finde igen. Små nyheder, arrangementer og det, der sker her og nu, ligger i <a href={facebook}>vores private Facebook-gruppe →</a></p></div></div><div className="newsGrid">{news.map((n,i)=><article className={i===0?'card featured':'card'} key={n.title}><span className="meta">{n.category}{n.date&&<> · {n.date}</>}</span><h3>{n.title}</h3><p>{n.body}</p>{n.href&&<a className="textLink" href={n.href}>{n.link}</a>}</article>)}</div></div></section>

<section id="hjertestarter" className="section cream"><div className="wrap areaFeature"><div><p className="eyebrow">Praktisk</p><h2>Hjertestarter</h2><p className="leadSmall">Foreningens hjertestarter hænger på Ravnsbjerg Krat 2.</p><p>Gå ind i carporten til højre. Hjertestarteren sidder bag den markerede dør til redskabsrummet.</p></div><div className="areaHeroPhoto heartPhoto"><img src={heart700} srcSet={`${heart700} 700w, ${heart} 1506w`} sizes="(max-width: 900px) calc(100vw - 28px), 48vw" width="1506" height="787" alt="Foreningens hjertestarter på Ravnsbjerg Krat 2" loading="lazy"/></div></div></section>

<section id="bestyrelsen" className="section"><div className="wrap"><div className="sectionHead"><div><p className="eyebrow">Kontakt</p><h2>Bestyrelsen</h2><p className="heroFacebook">Den nuværende bestyrelse efter generalforsamlingen 11. marts 2026.</p></div></div><div className="boardGrid">{board.map(m=><article key={m.name}><span>{m.role}</span><h3>{m.name}</h3><p>{m.address}</p>{m.phone&&<a href={'tel:+45'+m.phone.replaceAll(' ','')}>{m.phone}</a>}</article>)}</div></div></section>

<div id="kontakt" className="contact"><div className="wrap contactGrid" style={{alignItems:'start'}}><div><p className="eyebrow light">Kontakt bestyrelsen</p><h2>Skriv til bestyrelsen</h2><p>Spørgsmål, forslag eller noget fra området, vi bør kende til? Send en besked.</p></div><ContactForm/></div></div>

<section className="homeNext"><div className="wrap"><p className="eyebrow">Genveje</p><h2 className="homeNextTitle">Find videre</h2><nav className="homeNextGrid" aria-label="Find videre"><a href="#hjertestarter"><strong>Hjertestarter</strong><small>Placering og adgang</small><i aria-hidden="true">→</i></a><a href="#kontakt"><strong>Kontakt bestyrelsen</strong><small>Send en besked</small><i aria-hidden="true">→</i></a><a href="/lunden"><strong>Lunden</strong><small>Fælles område og haveaffald</small><i aria-hidden="true">→</i></a><a href="/omraadet"><strong>Ny i Ravnsbjerg</strong><small>Om området og det praktiske</small><i aria-hidden="true">→</i></a><a href="/generalforsamling"><strong>Generalforsamling</strong><small>Frister og referater</small><i aria-hidden="true">→</i></a><a href="/vedtaegter"><strong>Vedtægter</strong><small>Foreningens gældende regler</small><i aria-hidden="true">→</i></a></nav></div></section>
</main>}
