import {LocalMap} from '../../components/LocalMap'

const facebook='https://www.facebook.com/groups/ravnsbjerg'
const enge='https://398e19644f.clvaw-cdnwnd.com/924937a717deb337e31c66e81824097a/200000010-c8d10c8d12/IMG_1053.avif?ph=398e19644f'
const engeAerial='https://naturfonden.dk/wp-content/uploads/2021/05/FOTO-Tobias-Noergaard-Pedersen-Herning-Kommune-3.jpg'
const engeReport='https://398e19644f.clvaw-cdnwnd.com/924937a717deb337e31c66e81824097a/200000012-376e1376e4/%C3%85rsberetning%20for%20Gjellerup%20enge%202024.pdf?ph=398e19644f'

export const metadata={title:'Ny i Ravnsbjerg | Grundejerforeningen Ravnsbjerg',description:'Et kort overblik over Ravnsbjerg, Gjellerup Enge, skole, indkøb, Hall’n og årets faste arrangementer.'}

const wildlife=[
 {name:'Tredækker',latin:'Gallinago media',text:'En sjælden trækgæst, registreret i Gjellerup Enge i 2025.',img:'https://commons.wikimedia.org/wiki/Special:FilePath/Great%20Snipe%20%28Gallinago%20media%29%20%2814366171534%29.jpg',credit:'Ron Knight · CC BY 2.0',creditUrl:'https://commons.wikimedia.org/wiki/File:Great_Snipe_(Gallinago_media)_(14366171534).jpg'},
 {name:'Vibe',latin:'Vanellus vanellus',text:'En af de fugle, man kan opleve på de åbne og fugtige arealer.',img:'https://commons.wikimedia.org/wiki/Special:FilePath/Northern%20Lapwing%20Vanellus%20vanellus.jpg',credit:'Ivan Vezenković · CC0',creditUrl:'https://commons.wikimedia.org/wiki/File:Northern_Lapwing_Vanellus_vanellus.jpg'},
 {name:'Sanglærke',latin:'Alauda arvensis',text:'Høres og ses over de åbne enge og græsarealer.',img:'https://commons.wikimedia.org/wiki/Special:FilePath/Eurasian%20Skylark%20%28Alauda%20arvensis%29%20%2850715699017%29.jpg',credit:'Imran Shah · CC BY-SA 2.0',creditUrl:'https://commons.wikimedia.org/wiki/File:Eurasian_Skylark_(Alauda_arvensis)_(50715699017).jpg'},
 {name:'Bæver',latin:'Castor fiber',text:'Bæver er registreret ved Hammerum Bæk i området.',img:'https://commons.wikimedia.org/wiki/Special:FilePath/Beaver%20-%20Eurasian%20beaver%20-%20Castor%20fiber.jpg',credit:'Bouke ten Cate · CC BY 4.0',creditUrl:'https://commons.wikimedia.org/wiki/File:Beaver_-_Eurasian_beaver_-_Castor_fiber.jpg'},
 {name:'Okkergul pletvinge',latin:'Melitaea cinxia',text:'Sommerfuglen blev registreret i området i 2025.',img:'https://commons.wikimedia.org/wiki/Special:FilePath/Melitaea%20cinxia.png',credit:'Niclas Fritzén · CC BY 2.5',creditUrl:'https://commons.wikimedia.org/wiki/File:Melitaea_cinxia.png'}
]

export default function Omraadet(){return <main>
<section className="areaHero"><div className="wrap areaHeroGrid"><div><p className="eyebrow">Ravnsbjerg · Gjellerup</p><h1>Ny i Ravnsbjerg?</h1><p className="lead">Her er den korte udgave: hvor vi bor, hvad der ligger tæt på, og hvad der plejer at ske i løbet af året.</p><p className="areaIntro">Datoer, små nyheder og arrangementer kommer løbende i <a href={facebook} target="_blank" rel="noreferrer">Facebook-gruppen →</a></p></div><div className="areaHeroPhoto"><img src={enge} alt="Natur ved Gjellerup Enge"/></div></div></section>

<section className="section"><div className="wrap"><div className="sectionHead"><div><p className="eyebrow">Kort</p><h2>Det ligger tæt på</h2></div><p>Tryk på markeringerne for at se, hvad der ligger hvor.</p></div><LocalMap/><div className="nearbyGrid localPlaces"><article><span>🌿</span><h3>Gjellerup Enge</h3><p>144 hektar natur med stier, vand og græssende dyr lige ved området.</p></article><article><span>🏫</span><h3>Lindbjergskolen</h3><p>Folkeskole fra 0.-9. klasse på Frølundvej 39 mellem Gjellerup og Hammerum.</p></article><article><span>🛒</span><h3>Indkøb</h3><p>REMA 1000 på Klokkekildevej 23 er det nærmeste dagligvarested fra store dele af Ravnsbjerg.</p></article><article><span>⚽</span><h3>Hall’n</h3><p>Det lokale idræts- og samlingssted ligger ved Lindbjergskolen på Frølundvej 41.</p></article></div></div></section>

<section className="section cream"><div className="wrap"><div className="sectionHead"><div><p className="eyebrow">Året i foreningen</p><h2>Det plejer at gå sådan her</h2></div><p>De præcise datoer kommer på mail og i Facebook-gruppen.</p></div><div className="nearbyGrid yearGrid"><article><span>1.</span><h3>Generalforsamling</h3><p>Holdes i første kvartal.</p></article><article><span>2.</span><h3>Arbejdsdag</h3><p>Typisk i april eller maj. Vi ordner praktiske ting og får en snak undervejs.</p></article><article><span>3.</span><h3>Sankt Hans</h3><p>I juni plejer vi at mødes til Sankt Hans.</p></article><article><span>4.</span><h3>KSU</h3><p>I august er der Knyt Sammen Ugen, Hammerum-Gjellerups årlige byfest. Ravnsbjerg plejer blandt andet at stille et fodboldhold.</p><a className="textLink" href="https://knytsammen.dk/" target="_blank" rel="noreferrer">Se KSU →</a></article></div></div></section>

<section id="gjellerup-enge" className="section soft"><div className="wrap"><div className="sectionHead"><div><p className="eyebrow">Natur lige ved siden af</p><h2>Gjellerup Enge</h2></div><p>Et stort naturprojekt mellem Gjellerup, Hammerum og Birk.</p></div><div className="engeIntro"><p className="leadSmall">Gjellerup Enge er 144 hektar sammenhængende natur. Området består blandt andet af enge, kær, overdrev, skov og krat, og Hammerum Bæk løber gennem den sydlige del.</p><p>Her er omkring tre kilometer stier, og heste og kvæg græsser i området. Regnvandsbassiner fra kloaksepareringen i Hammerum er blevet en del af landskabet, og jord fra bassinerne er brugt til en cirka 10 meter høj udkigsbakke.</p><p>Det er med andre ord ikke bare et grønt areal ved siden af kvarteret. Det er et område, hvor vandhåndtering, natur og adgang for gående er tænkt sammen.</p><div className="docLinks"><a href="https://naturfonden.dk/natur/gjellerup-enge/" target="_blank" rel="noreferrer">Læs hos Den Danske Naturfond →</a><a href={engeReport} target="_blank" rel="noreferrer">Årsberetning 2024 →</a></div></div><div className="areaFacts fourFacts"><article><span>144 ha</span><h3>Natur</h3><p>Enge, kær, overdrev, skov, krat og vådområder.</p></article><article><span>ca. 3 km</span><h3>Stier</h3><p>Til fods gennem området, også gennem indhegninger med dyr.</p></article><article><span>10 m</span><h3>Udkigsbakke</h3><p>Bygget af jord fra de nye regnvandsbassiner.</p></article><article><span>1.203</span><h3>Arter</h3><p>Registreret på iNaturalist ved udgangen af 2025.</p></article></div><div className="areaPhotoWide creditedPhoto"><img src={engeAerial} alt="Luftfoto af Gjellerup Enge med Hammerum Bæk"/><small className="photoCredit">Foto: Tobias Nørgaard Pedersen / Herning Kommune</small></div></div></section>

<section className="section"><div className="wrap areaFeature"><div><p className="eyebrow">iNaturalist</p><h2>Se fundene på kortet</h2><p className="leadSmall">Lokale naturfolk og andre besøgende registrerer løbende dyr, planter og svampe i Gjellerup Enge.</p><p>Ved udgangen af 2025 var der registreret 1.203 arter på iNaturalist. Kortet giver et ret godt billede af, hvor meget der faktisk bliver fundet i området.</p><div className="pageActions"><a className="button primary" href="https://www.inaturalist.org/projects/gjellerup-enge" target="_blank" rel="noreferrer">Åbn Gjellerup Enge på iNaturalist</a></div><p className="smallNote">Der findes også registreringer på <a href="https://arter.dk/faellesskaber/2017" target="_blank" rel="noreferrer">Arter.dk</a>.</p></div><div className="mapFrame inatFrame"><iframe title="iNaturalist-observationer fra Gjellerup Enge" src="https://www.inaturalist.org/places/196123/widget" loading="lazy"></iframe></div></div></section>

<section className="section soft"><div className="wrap"><div className="sectionHead"><div><p className="eyebrow">Dyreliv</p><h2>Det kan du opleve i Gjellerup Enge</h2></div><p>Et par eksempler blandt de mange registrerede arter.</p></div><div className="wildlifeGrid">{wildlife.map(w=><article className="wildlifeCard" key={w.name}><img src={w.img} alt={w.name} loading="lazy"/><div className="wildlifeBody"><p className="eyebrow">{w.latin}</p><h3>{w.name}</h3><p>{w.text}</p><a href={w.creditUrl} target="_blank" rel="noreferrer">Foto: {w.credit}</a></div></article>)}</div><p className="smallNote">Artsbillederne er illustrationsfotos og er ikke nødvendigvis taget i Gjellerup Enge.</p></div></section>

<section className="section"><div className="wrap"><div className="sectionHead"><div><p className="eyebrow">Også tæt på</p><h2>To steder mere</h2></div></div><div className="simpleLinks localLinks"><a href="/sport"><small>Sport og fritid</small><h3>Hall’n</h3><p>Se de lokale idrætsmuligheder.</p></a><a href="/hammerum-pigen"><small>Lokalhistorie</small><h3>Hammerum-pigen</h3><p>Læs om gravfundet ved Ny Gjellerupvej.</p></a></div></div></section>
</main>}
