const enge='https://398e19644f.clvaw-cdnwnd.com/924937a717deb337e31c66e81824097a/200000010-c8d10c8d12/IMG_1053.avif?ph=398e19644f'
const lunden1='https://398e19644f.clvaw-cdnwnd.com/924937a717deb337e31c66e81824097a/200000035-7bee97beec/ea6e5aa3-1b01-47d3-8fd4-1cae02db549f.jpeg?ph=398e19644f'
const lunden2='https://398e19644f.clvaw-cdnwnd.com/924937a717deb337e31c66e81824097a/200000036-936cb936cd/df6156b8-e6cd-4fd6-a62d-a817fed3fcd0-8.jpeg?ph=398e19644f'

export const metadata={title:'Om området | Grundejerforeningen Ravnsbjerg',description:'Kort og lokale steder omkring Ravnsbjerg, Lunden og Gjellerup Enge.'}

const places=[
 {n:'Ravnsbjerg',t:'Her tager kortet udgangspunkt. Kvarteret ligger mellem Gjellerup, de grønne arealer og forbindelserne mod Hammerum.',q:'Ravnsbjerg Krat, 7400 Herning'},
 {n:'Lunden',t:'Grundejerforeningens eget rekreative område – lige ved kvarteret og med adgang for medlemmerne.',q:'Ravnsbjerg Mark, 7400 Herning'},
 {n:'Gjellerup Enge',t:'Det store naturprojekt med enge, stier og helårsgræsning ligger tæt på Ravnsbjerg.',q:'Gjellerup Enge, Herning'},
 {n:'Lindbjergskolen',t:'Skole, bibliotek og en del af det lokale hverdagsliv i Hammerum-Gjellerup.',q:'Lindbjergskolen, Herning'},
 {n:'Gjellerup Kirke',t:'Den gamle kirke og landsbykerne ligger nord for kvarteret.',q:'Gjellerup Kirke, Herning'}
]

export default function Omraadet(){return <main>
<section className="areaHero"><div className="wrap areaHeroGrid"><div><p className="eyebrow">Ravnsbjerg · Gjellerup</p><h1>Her bor vi</h1><p className="lead">Et roligt villakvarter med byen tæt på og naturen endnu tættere.</p><p className="areaIntro">Lunden ligger ved kvarteret, og derfra er det nemt at komme videre ud på stierne omkring Gjellerup. Mod øst og syd ligger Gjellerup Enge med et stort sammenhængende naturområde.</p></div><div className="areaHeroPhoto"><img src={enge} alt="Natur ved Gjellerup Enge"/></div></div></section>

<section className="section areaMapSection"><div className="wrap"><div className="sectionHead"><div><p className="eyebrow">Find rundt</p><h2>Se området på kortet</h2></div><p>Zoom ud, og man får hurtigt et billede af, hvordan Ravnsbjerg ligger mellem Gjellerup, Hammerum og de grønne områder.</p></div><div className="mapFrame"><iframe title="Kort over Ravnsbjerg og Gjellerup" src="https://www.google.com/maps?q=Ravnsbjerg+Krat,+7400+Herning&z=14&output=embed" loading="lazy" referrerPolicy="no-referrer-when-downgrade"></iframe></div><div className="mapPlaces">{places.map(p=><a key={p.n} href={'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(p.q)} target="_blank" rel="noreferrer"><b>{p.n}</b><span>{p.t}</span><i>Se på kort →</i></a>)}</div></div></section>

<section className="section soft"><div className="wrap areaFeature"><div className="areaGallery"><img src={lunden1} alt="Lunden ved Ravnsbjerg"/><img src={lunden2} alt="Natur i Lunden"/></div><div><p className="eyebrow">Lige ved kvarteret</p><h2>Lunden</h2><p className="leadSmall">Lunden er grundejerforeningens eget grønne område og en ret særlig del af Ravnsbjerg.</p><p>Det er et sted, man kan bruge uden at gøre et stort nummer ud af det: en tur med hunden, en gåtur eller bare en vej videre ud i området. Fra Ravnsbjerg er der forbindelse mod stierne omkring Gjellerup.</p><a className="button secondary" href="/#lunden">Mere om Lunden</a></div></div></section>

<section className="section"><div className="wrap"><div className="sectionHead"><div><p className="eyebrow">Natur tæt på</p><h2>Gjellerup Enge</h2></div><p>Et stort sammenhængende naturområde lige i nærheden.</p></div><div className="areaFacts"><article><span>144 ha</span><h3>Plads til natur</h3><p>Herning Kommune oplyser, at projektområdet omfatter 144 hektar mose, eng og tidligere landbrugsjord, der nu forvaltes med natur som formål.</p></article><article><span>Året rundt</span><h3>Dyr på arealerne</h3><p>Der går dyr på arealerne hele året. Det er en del af naturplejen, så nogle af turene går gennem indhegninger med græssende dyr.</p></article><article><span>630 m</span><h3>Bedre stiforbindelse</h3><p>I 2024 fik cirka 630 meter af stien mellem Napkærstien og Ravnsbjergskoven fast underlag. Kommunen har også arbejdet med afmærkning, så området er lettere at finde rundt i.</p></article></div><div className="areaPhotoWide"><img src={enge} alt="Gjellerup Enge"/></div></div></section>

<section className="section cream"><div className="wrap"><div className="sectionHead"><div><p className="eyebrow">I hverdagen</p><h2>Tæt på det meste</h2></div><p>Ravnsbjerg ligger ikke langt ude på landet – selv om der er meget grønt omkring os.</p></div><div className="nearbyGrid"><article><span>↗</span><h3>Skole og bibliotek</h3><p>Lindbjergskolen og biblioteket ligger i Hammerum-Gjellerup og kan nås via områdets vej- og stiforbindelser.</p></article><article><span>↗</span><h3>Indkøb</h3><p>Der er flere dagligvarebutikker i Hammerum-Gjellerup, blandt andet SuperBrugsen, Rema 1000 og 365discount.</p></article><article><span>↗</span><h3>Sport og foreninger</h3><p>Hammerum-Gjellerup har et aktivt foreningsliv med sport, spejdere og andre lokale aktiviteter.</p></article><article><span>↗</span><h3>Ud at gå</h3><p>Kommunens stier i Gjellerup Enge består af både fast belægning, grus og mere enkle trampestier.</p></article></div></div></section>

<section className="section"><div className="wrap"><div className="sectionHead"><div><p className="eyebrow">Mere om nærområdet</p><h2>To steder at dykke videre ned</h2></div><p>Både det lokale foreningsliv og områdets historie fortjener lidt mere plads.</p></div><div className="areaDeepLinks"><a href="/sport"><span>⚽</span><div><small>Sport & fritid</small><h3>Hall’n og idrætsmulighederne</h3><p>Se hvad man kan gå til i Hammerum-Gjellerup – fra fodbold og svømning til padel, fitness og badminton.</p><b>Se sport og fritid →</b></div></a><a href="/hammerum-pigen"><span>⌛</span><div><small>Lokalhistorie</small><h3>Hammerum-pigen</h3><p>Historien om den usædvanligt velbevarede kvindegrav fra romersk jernalder ved Ny Gjellerupvej.</p><b>Læs historien →</b></div></a></div></div></section>

<section className="areaSources"><div className="wrap"><h3>Oplysninger om området</h3><p>Natur- og stioplysningerne er baseret på Herning Kommunes materiale om Gjellerup Enge. Oplysninger om lokale tilbud er suppleret med Hammerum-Gjellerup Borgerforenings oversigt. Kort og vejvisning leveres af Google Maps.</p><div className="docLinks"><a href="https://www.herning.dk/Media/638753951289819434/%C3%85rsrapport%20for%20Natur%20og%20Gr%C3%B8nne%20Omr%C3%A5der%202024.pdf" target="_blank" rel="noreferrer">Herning Kommune – Naturindsatsen 2024 →</a><a href="https://hammerum-gjellerup-borgerforening.dk/" target="_blank" rel="noreferrer">Hammerum-Gjellerup Borgerforening →</a></div></div></section>
</main>}
